major refactoring to add more utility commands

diff --git a/git-remote-rclone-sync b/git-remote-rclone-sync
--- a/git-remote-rclone-sync
+++ b/git-remote-rclone-sync
@@ -24,55 +24,203 @@
 ##
 
 
-#
-#  git-remote-rclone-sync/-mount: pull and push to Git remotes via rclone
-#
-#  This remote can operate in either of two ways:
-#
-#   1. Using "rclone sync", which involves keeping a full local copy of
-#      the remote repository.  This is the default, and should in most
-#      cases result in fewer accesses/less egress bandwith used.
-#
-#   2. Using "rclone mount" to access the remote repository via a FUSE
-#      filesystem mount.  This trades less local disk usage for more
-#      intensive network access.
-#
-#  Example usages (sync mode):
-#
-#      git clone rclone-sync::name_of_remote:path/to/repository.git
-#      git remote add foo rclone-sync::foo:path/to/foo.git
-#
-#  Example usages (mount mode):
-#
-#      git clone rclone-mount::name_of_remote:path/to/repository.git
-#      git remote add foo rclone-mount::foo:path/to/foo.git
-#
-#  The remote location is assumed to contain a Git repository -
-#  preferably a bare repository (ordinary repositories should work OK
-#  but using these as a remote isn't good practice).
-#
-#  Neither of the two modes of operation attempts to detect or remedy
-#  situations where another process is accessing the remote repository
-#  concurrently.  To avoid corruption, only use this tool in use cases
-#  where concurrent access is unlikely, or implement your own mechanism
-#  to arbitrate access.
-#  
-#  This script would have just been called "git-remote-rclone", but
-#  that name is already taken on GitHub and PyPI by another script
-#  which uses a non-standard remote repository format.
-#
+
+function usage() {
+    cat <<"__USAGE__"
+Usage: $0 REMOTE_NAME RCLONE_REMOTE_NAME:PATH
+   or: $0 --init RCLONE_REMOTE_NAME:PATH
+   or: $0 [--fsck|--gc|--repack] [--remote GIT_REMOTE_NAME]
+   or: $0 --password-helper [RCLONE_CONFIG_PATH]
+   or: $0 [--help|--longhelp|--version]
+__USAGE__
+}
+
+
+function options() {
+    cat <<'__OPTIONS__'
+  --init RCLONE_REMOTE_NAME:PATH [DESCRIPTION]
+        create a nearly-empty bare git repository at RCLONE_REMOTE_NAME:PATH
+        with a placeholder README.md file, optionally containing DESCRIPTION
+  --fsck
+        run git-fsck(1) on the remote repository - subsequent arguments
+        (except --remote) are passed to `git fsck`
+  --gc
+        run git-gc(1) on the remote repository - subsequent arguments
+        (except --remote) are passed to `git gc`
+  --repack
+        run git-repack(1) on the remote repository - subsequent arguments
+        (except --remote) are passed to `git repack`
+  --remote GIT_REMOTE_NAME
+        which remote of the current git working directory fsck/gc/repack
+        should affect, if more than one uses rclone-sync
+  --password-helper [RCLONE_CONFIG_PATH]
+        called internally by rclone to obtain the rclone config password
+        from the gitcredentials(7) infrastructure
+  --help
+        print brief usage info
+  --longhelp
+        print full usage info
+  --version
+        print version info
+__OPTIONS__
+}
+
+
+function longhelp() {
+    usage
+    echo
+    sed -e "s:SCHEME_NAME:${SCHEME_NAME}:g" <<'__LONGHELP_1__'
+Pull and push to Git remote repositories via rclone.
+
+In most cases a user shouldn't need to invoke this tool directly -
+it is called internally by git whenever accessing a remote repository
+whose URL starts with `SCHEME_NAME::` (see gitremote-helpers(7) for
+the gory details).
+
+For convenience some options have been added, mostly to aid in
+setting up and maintaining remote repositories.
+__LONGHELP_1__
+    echo
+    options
+    echo
+    sed -e "s:SCHEME_NAME:${SCHEME_NAME}:g" <<'__LONGHELP_2__'
+Cloning a repository via rclone is straightforward:
+
+    git clone SCHEME_NAME::name-of-rclone-remote:path/to/repository.git
+
+Alternately you can add an rclone-based remote to an existing working copy:
+
+    git remote add foo SCHEME_NAME::name-of-rclone-remote:path/to/repo.git
+    git push foo
+
+Pushes and pulls to a remote location won't work unless a git repository
+already exists there.  The `--init` option to this tool can be used to 
+conveniently create a minimal remote repository if none exists.
+__LONGHELP_2__
+    echo
+    if [[ "${SCHEME_NAME}" == rclone-sync ]]
+    then
+        cat <<'__LONGHELP_3A__'
+This tool keeps a full copy of the remote repository in your working copy's
+`.git` directory, which is kept in sync with the remote.  You can also invoke
+this tool as `git-remote-rclone-mount` (using repository URLs starting with
+`rclone-mount::`) to access the remote via a FUSE mount instead, at a cost of
+more intensive network access and reduced reliability/performance.
+__LONGHELP_3A__
+    elif [[ "${SCHEME_NAME}" == rclone-mount ]]
+    then
+        cat <<'__LONGHELP_3B__'
+This tool uses `rclone mount` to access the remote repository via FUSE.
+You can also invoke this tool as `git-remote-rclone-sync` (using repository
+URLs starting with `rclone-sync::` to instead use a full local copy of the
+remote repository which is kept in sync - this uses more local disk space but
+is typically more performant and reliable.
+__LONGHELP_3B__
+    fi
+    echo
+    sed -e "s:SCHEME_NAME:${SCHEME_NAME}:g" <<'__LONGHELP_4__'
+A custom rclone config file can be stored under your working copy's `.git`
+directory, at `.git/SCHEME_NAME/rclone.conf` - this will supersede the
+user/system rclone configuration if present.
+
+CAUTION: Attempts by multiple users to concurrently modify the remote
+repository may lead to corruption.  Only use this tool in cases where
+concurrent modification by multiple users is unlikely.
+
+Home page: <https://github.com/pobrelkey/git-remote-rclone-sync>
+Reporting bugs: <https://github.com/pobrelkey/git-remote-rclone-sync/issues>
+__LONGHELP_4__
+}
+
+
+# Run a command over (a copy of) the remote repository, syncing changes
+# from the remote beforehand, and back to the remote afterwards if needed.
+function with_repo() {
+    REMOTE_COPY_DIR="${GIT_DIR}/${REMOTE_SCHEME}/remotes/${REMOTE_URI/://}"
+
+    # If an rclone config file exists at .git/rclone-sync/rclone.conf,
+    # use that in preference to the system rclone config file.
+    if [[ -e "${GIT_DIR}/${REMOTE_SCHEME}/rclone.conf" ]]
+    then
+        export RCLONE_CONFIG="${GIT_DIR}/${REMOTE_SCHEME}/rclone.conf"
+    fi
+
+    # Source .git/rclone-sync/rclone.conf if it exists, to optionally set
+    # environment variables used by rclone.
+    if [[ -e "${GIT_DIR}/${REMOTE_SCHEME}/config.env" ]]
+    then
+        . "${GIT_DIR}/${REMOTE_SCHEME}/config.env"
+    fi
+
+    # If no rclone password helper is already specified, tell rclone to
+    # invoke this script with --password-helper if it needs a password for
+    # its config file.  (Rclone's built-in password prompt won't work.)
+    export RCLONE_PASSWORD_COMMAND="${RCLONE_PASSWORD_COMMAND:-\"${0//\"/\"\"}\" --password-helper \"${RCLONE_CONFIG//\"/\"\"}\"}"
+
+    READ_WRITE_MODE="${1}"
+    shift
+    VERB="${1}"
+    shift
+
+    mkdir -p "${REMOTE_COPY_DIR}" 1>&2
+    if [[ "${REMOTE_SCHEME%mount}" != "${REMOTE_SCHEME}" ]]
+    then
+        function umount_rclone() {
+            # Try to unmount the remote repo platform-agnostically:
+            if [[ -x "$(which fusermount 2>/dev/null || true)" ]]
+            then
+                # if "fusermount" is on the path (Linux), use that
+                fusermount -uz "${REMOTE_COPY_DIR}" 1>&2
+            elif [[ "$(uname -o)" == Darwin ]]
+            then
+                # if we're on Mac OS, use "disktool"
+                disktool unmount "${REMOTE_COPY_DIR}" 1>&2
+            else
+                # try "umount" - this is the correct way on *BSD
+                umount "${REMOTE_COPY_DIR}" 1>&2
+            fi
+        }
+        trap umount_rclone EXIT
+        rclone mount "${REMOTE_URI}/" "${REMOTE_COPY_DIR}/" 1>&2 &
+
+        # HACK: wait up to 10s until remote is actually mounted
+        for i in $(seq 1 100)
+        do
+            if [[ -e "${REMOTE_COPY_DIR}/HEAD" ]] || [[ -e "${REMOTE_COPY_DIR}/.git/HEAD" ]]
+            then
+                break
+            fi
+            sleep 0.1
+        done
+    else
+        find "${REMOTE_COPY_DIR}" -type f -not -writable | xargs -r chmod u+w
+        rclone sync --create-empty-src-dirs "${REMOTE_URI}/" "${REMOTE_COPY_DIR}/" 1>&2
+    fi
+
+    "${VERB}" "${REMOTE_COPY_DIR}" "${@}"
+
+    if [[ "${READ_WRITE_MODE}" == --rw ]] && [[ "${REMOTE_SCHEME%mount}" == "${REMOTE_SCHEME}" ]]
+    then
+        rclone sync --create-empty-src-dirs "${REMOTE_COPY_DIR}/" "${REMOTE_URI}/" 1>&2
+    fi
+
+    exit 0
+}
+
 
 
 set -e
 
-
 if [[ $# == 0 ]]
 then
-    # TODO: proper usage message
-    echo "ERROR: specify --init or let git call this script internally (see \"man gitremote-helpers\")" 1>&2
+    usage 1>&2
     exit 1
 fi
 
+REMOTE_SCHEME="$(basename "${0}")"
+REMOTE_SCHEME="${REMOTE_SCHEME#git-remote-}"
+
+# Was this script called with an --option?  If so, handle as appropriate...
 case "${1}" in
     --password-helper)
         # If the script is invoked with --pasword-helper as the first arg,
@@ -142,7 +290,6 @@ case "${1}" in
         done
         ;;
 
-
     --init)
         # For convenience: initialize a repository on an rclone remote.
         # (Repositories stored on S3 and other backends with no concept of
@@ -203,15 +350,53 @@ case "${1}" in
 
 
     --fsck|--gc|--repack)
-        # TODO
-        echo "ERROR: not implemented yet: ${1}" 1>&2
-        exit 1
+        # we're in a Git working dir I hope...
+        GIT_DIR="${GIT_DIR:-$(git rev-parse --absolute-git-dir)}"
+        if [[ ! -d "${GIT_DIR}" ]]
+        then
+            echo "ERROR: not in a git working directory or GIT_DIR not defined" 1>&2
+            exit 1
+        fi
+
+        CMD="${1#--}"
+        shift
+
+        # figure out which remote needs to be tweaked
+        if [[ "$1" == --remote ]]
+        then
+            shift
+            REMOTE_NAME="$1"
+            shift
+            REMOTE_URI="$(git remote get-uri ${REMOTE_NAME})"
+        else
+            REMOTE_COUNT=$(( "$(git remote -v | grep -E "\\t${REMOTE_SCHEME}::" | wc -l)" / 2 ))
+            if [[ $REMOTE_COUNT != 1 ]]
+            then
+                echo "ERROR: working dir has more than one ${REMOTE_SCHEME} remote - use --remote flag to specify a specific one" 1>&2
+                exit 1
+            fi
+            REMOTE_URI="$(git remote -v | grep -Eo "${REMOTE_SCHEME}::[^ ]+" | head -1)"
+        fi
+
+        function do_command() {
+            export GIT_DIR=
+            REPO_DIR="$1"
+            shift
+            git -C "${REPO_DIR}" "$@"
+        }
+        with_repo --rw do_command "${CMD}" "$@"
         ;;
 
     --help)
-        # TODO
-        echo "ERROR: not implemented yet: ${1}" 1>&2
-        exit 1
+        usage
+        echo
+        options
+        exit 0
+        ;;
+
+    --longhelp)
+        longhelp
+        exit 0
         ;;
 
     --version)
@@ -226,33 +411,15 @@ case "${1}" in
 
     --*)
         echo "ERROR: unrecognized option: ${1}" 1>&2
+        usage 1>&2
         exit 1
 
 esac
 
 
 
-REMOTE_SCHEME="$(basename "${0}")"
-REMOTE_SCHEME="${REMOTE_SCHEME#git-remote-}"
-
-# If an rclone config file exists at .git/rclone-sync/rclone.conf,
-# use that in preference to the system rclone config file.
-if [[ -e "${GIT_DIR}/${REMOTE_SCHEME}/rclone.conf" ]]
-then
-    export RCLONE_CONFIG="${GIT_DIR}/${REMOTE_SCHEME}/rclone.conf"
-fi
-
-# Source .git/rclone-sync/rclone.conf if it exists, to optionally set
-# environment variables used by rclone.
-if [[ -e "${GIT_DIR}/${REMOTE_SCHEME}/config.env" ]]
-then
-    . "${GIT_DIR}/${REMOTE_SCHEME}/config.env"
-fi
-
-# If no rclone password helper is already specified, tell rclone to
-# invoke this script with --password-helper if it needs a password for
-# its config file.  (Rclone's built-in password prompt won't work.)
-export RCLONE_PASSWORD_COMMAND="${RCLONE_PASSWORD_COMMAND:-\"${0//\"/\"\"}\" --password-helper \"${RCLONE_CONFIG//\"/\"\"}\"}"
+# No options specified, so we're being called internally by Git -
+# so start a session in which we implement the Git remote protocol.
 
 if [[ -z "${2}" ]]
 then
@@ -260,8 +427,6 @@ then
 else
     REMOTE_URI="${2}"
 fi
-
-REMOTE_COPY_DIR="${GIT_DIR}/${REMOTE_SCHEME}/remotes/${REMOTE_URI/://}"
 
 while true
 do
@@ -284,39 +449,27 @@ do
             ;;
 
         connect)
-            mkdir -p "${REMOTE_COPY_DIR}" 1>&2
-            if [[ "${REMOTE_SCHEME%mount}" != "${REMOTE_SCHEME}" ]]
+            if [[ -z "${2}" ]]
             then
-                function umount_rclone() {
-                    # TODO: next line needs to be different on non-Linux OSes
-                    fusermount -uz "${REMOTE_COPY_DIR}/" 1>&2
-                }
-                trap umount_rclone EXIT
-                rclone mount "${REMOTE_URI}/" "${REMOTE_COPY_DIR}/" 1>&2 &
-
-                # HACK: wait up to 10s until remote is actually mounted
-                for i in $(seq 1 100)
-                do
-                    if [[ -e "${REMOTE_COPY_DIR}/HEAD" ]] || [[ -e "${REMOTE_COPY_DIR}/.git/HEAD" ]]
-                    then
-                        break
-                    fi
-                    sleep 0.1
-                done
+                REMOTE_URI="${1}"
             else
-                find "${REMOTE_COPY_DIR}" -type f '!' -perm -0200 -exec chmod u+w {} +
-                rclone sync --create-empty-src-dirs "${REMOTE_URI}/" "${REMOTE_COPY_DIR}/" 1>&2
+                REMOTE_URI="${2}"
             fi
-
-            echo
-            "${ARG}" "${REMOTE_COPY_DIR}"
-
-            if [[ "${ARG}" != git-upload-pack ]] && [[ "${REMOTE_SCHEME%mount}" == "${REMOTE_SCHEME}" ]]
+            function do_command() {
+                echo
+                ARG="$1"
+                shift
+                CMD="$1"
+                shift
+                "${CMD}" "${ARG}" "$@"
+            }
+            if [[ "${ARG}" == git-upload-pack ]]
             then
-                rclone sync --create-empty-src-dirs "${REMOTE_COPY_DIR}/" "${REMOTE_URI}/" 1>&2
+                READ_WRITE_MODE=--ro
+            else
+                READ_WRITE_MODE=--rw
             fi
-
-            exit 0
+            with_repo $READ_WRITE_MODE do_command "${ARG}"
             ;;
 
         *)
